package com.insideinvoice.labels.render;

import com.insideinvoice.labels.enums.LabelPreset;
import com.insideinvoice.labels.renderer.PdfCanvas;
import com.insideinvoice.labels.util.LabelUnits;

import java.io.IOException;

/**
 * "Simple Address" — minimal layout: FROM block on top, oversized ship-to
 * block below, tracking barcode + footer. No routing zone or service box;
 * suited to tiny thermal sizes (100x100, 4x4, 4x3).
 */
public class SimpleAddressRenderer extends StandardCarrierRenderer {

    @Override
    public LabelPreset preset() {
        return LabelPreset.SIMPLE_ADDRESS;
    }

    @Override
    protected void drawInstance(PdfCanvas canvas, ShippingLabelSpec spec, int index, int total,
                                double wMm, double hMm) throws IOException {
        double m = LabelSizes.SAFE_MARGIN_MM;
        if (spec.isBorder()) {
            canvas.strokeRect(0.5, 0.5, wMm - 1, hMm - 1, LabelSizes.KEYLINE_MM);
        }
        double cw = wMm - 2 * m;
        double bottom = hMm - m;
        double footerTop = bottom - LabelSizes.ZONE5_FOOTER_MM;

        // zone 1: FROM (compact — 2-3 lines)
        double z1 = m;
        double fromH = Math.min(14, Math.max(10, hMm * 0.1));
        double y = z1 + 0.5;
        canvas.text("FROM:", m, y, LabelSizes.T_CAPTION, true, PdfCanvas.Align.LEFT);
        y += LabelUnits.ptToMm(LabelSizes.T_CAPTION * LabelSizes.LINE_HEIGHT) + 0.2;
        drawAddressLines(canvas, spec.getShipFrom(), m, y, cw * 0.55,
                z1 + fromH - 0.5, LabelSizes.T_SHIP_FROM);
        canvas.text(upper(spec.getCarrier(), ""), m + cw, z1 + 0.5,
                7.5, true, PdfCanvas.Align.RIGHT);
        double rule1 = z1 + fromH;
        rule(canvas, rule1, m, wMm);

        // zone 2: ship-to (gets most of the height)
        double rule2 = footerTop - LabelSizes.RULE_MM - LabelSizes.ZONE5_FOOTER_MM * 0;
        double barZoneH = Math.min(26, Math.max(18, hMm * 0.22));
        double rule2Y = footerTop - LabelSizes.RULE_MM - barZoneH;
        double shipH = rule2Y - rule1 - LabelSizes.RULE_MM;

        double y2 = rule1 + LabelSizes.RULE_MM + 0.8;
        double budget = rule1 + LabelSizes.RULE_MM + shipH - 0.5;
        LabelAddress to = spec.getShipTo();
        String name = upper(to == null ? "" : to.getName(), "RECIPIENT");
        double nameSize = canvas.fitFontSize(name, cw - 4, LabelSizes.T_SHIP_TO_NAME, 9, true);
        canvas.text(name, m + 3.5, y2, nameSize, true, PdfCanvas.Align.LEFT);
        y2 += LabelUnits.ptToMm(nameSize * LabelSizes.LINE_HEIGHT);
        if (to != null && !blank(to.getCompany())) {
            String co = to.getCompany().toUpperCase(java.util.Locale.ENGLISH);
            double s = canvas.fitFontSize(co, cw - 4, 10, 7, true);
            canvas.text(co, m + 3.5, y2, s, true, PdfCanvas.Align.LEFT);
            y2 += LabelUnits.ptToMm(s * LabelSizes.LINE_HEIGHT);
        }
        String addrText = to == null ? "" : to.joinedLines();
        int maxLines = 4;
        if (!addrText.isEmpty()) {
            y2 = canvas.drawParagraph(addrText.toUpperCase(java.util.Locale.ENGLISH),
                    m + 3.5, y2, cw - 4, LabelSizes.T_SHIP_TO_ADDR, 7.5, maxLines, true,
                    PdfCanvas.Align.LEFT);
        }
        String city = to == null ? "" : to.cityLine().toUpperCase(java.util.Locale.ENGLISH);
        if (!city.isEmpty() && y2 < budget - 3) {
            double s = canvas.fitFontSize(city, cw - 4, 11.5, 9, true);
            canvas.text(city, m + 3.5, y2, s, true, PdfCanvas.Align.LEFT);
        }
        rule(canvas, rule1 + LabelSizes.RULE_MM + shipH, m, wMm);

        // zone 3: tracking barcode
        double barTop = rule1 + LabelSizes.RULE_MM + shipH + LabelSizes.RULE_MM;
        if (!blank(spec.trackingForIndex(index))) {
            double barH = Math.min(LabelSizes.BARCODE_H_MM, barZoneH - 7);
            double barBottom = canvas.barcodeLinear(
                    com.insideinvoice.labels.util.BarcodeUtils.code128(spec.trackingForIndex(index)),
                    m, barTop + 0.8, cw, barH, 10, 2);
            String hrt = groupTracking(spec.trackingForIndex(index));
            double hs = canvas.fitFontSize(hrt, cw - 2, LabelSizes.T_BARCODE_TEXT, 7, true);
            canvas.text(hrt, wMm / 2, barBottom + 1, hs, true, PdfCanvas.Align.CENTER);
        }

        rule(canvas, footerTop - LabelSizes.RULE_MM, m, wMm);
        drawFooter(canvas, spec, index, total, footerTop, wMm, m, cw);
    }

    private void drawFooter(PdfCanvas canvas, ShippingLabelSpec spec, int index, int total,
                            double footerTop, double wMm, double m, double cw) throws IOException {
        double y = footerTop + 1.6;
        canvas.text("Generated by " + spec.footerIdentity(), m, y, LabelSizes.T_FOOTER, false,
                PdfCanvas.Align.LEFT);
        String right = nv(spec.getLabelNumber()) + "  " + index + "/" + total;
        double size = canvas.fitFontSize(right, cw * 0.5, LabelSizes.T_FOOTER, 6, false);
        canvas.text(right, wMm - m, y, size, false, PdfCanvas.Align.RIGHT);
    }
}
