server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: inside-invoice
  profiles:
    active: local

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd
    time-zone: UTC

app:
  jwt:
    secret: 4a6f686e446f6553656372657456657279566572795365637265744b6579466f724a57545369676e696e67416e64456e6372797074696f6e
    expiration-ms: 21600000
    refresh-expiration-ms: 2592000000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: Inside Invoice
    description: SaaS Multi-Tenant Invoicing Platform
    version: 1.0.0
