ALTER TABLE businesses
ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS account_no VARCHAR(255),
ADD COLUMN IF NOT EXISTS branch VARCHAR(255),
ADD COLUMN IF NOT EXISTS ifsc VARCHAR(50),
ADD COLUMN IF NOT EXISTS bank_address TEXT;
